In [56]:
pip install sklearn

Note: you may need to restart the kernel to use updated packages.


In [57]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [58]:
import warnings
warnings.filterwarnings("ignore")

In [59]:
hp = pd.read_csv("/Users/kishore/Documents/Kishore/Bloomington/Data Science/Machinelearning practice/py-master/ML/1_linear_reg/homeprices.csv")

In [60]:
hp

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [61]:
reg = linear_model.LinearRegression()
reg.fit(hp[["area"]],hp.price)

LinearRegression()

In [62]:
reg.coef_

array([135.78767123])

In [63]:
reg.intercept_

180616.43835616432

In [64]:
reg.predict([[3000]])

array([587979.45205479])

### Pickle

In [65]:
import pickle

#### we open a file(reg) in write binary(wb) mode and dump it in new file (reg_pickle) new file will be created using this name.


In [66]:
with open("reg_pickle",  "wb") as f:
    pickle.dump(reg,f)

#### To load the same file(reg_pickle) into some other memory (mb) initially we need to open the file and then load it

In [67]:
with open("reg_pickle",  "rb") as f:
    mb = pickle.load(f)

#### now we can use the memory (mb) to predict the price

In [68]:
mb.predict([[3000]])

array([587979.45205479])

In [69]:
mb.intercept_

180616.43835616432

In [70]:
mb.coef_

array([135.78767123])

### Joblib

In [71]:
import joblib
joblib.dump(reg, "reg_joblib")

['reg_joblib']

In [72]:
mj = joblib.load("reg_joblib")

In [73]:
mj.predict([[3000]])

array([587979.45205479])

In [74]:
mj.intercept_

180616.43835616432

In [75]:
mj.coef_

array([135.78767123])

### Joblib and Pickle does the same work but when we have large number of numpy arrays joblib is efficient compared to pickle.